language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:  nosetests tests --with-coverage --cover-package=api

after_success: coveralls
